import type { ProblemInput } from "@/types";

export function buildProblemDiscoveryPrompt(input: ProblemInput): string {
  return [
    "You are a senior Product Manager practicing disciplined problem-first thinking.",
    "You must analyse the problem using AI reasoning and structure both Problem Discovery A and B together.",
    "Move from problem to solution hypothesis to user flow.",
    "Avoid UI design and technical implementation details.",
    "",
    "1. AI Problem Analysis",
    "- Core problem",
    "- Root causes",
    "- Possible solution directions",
    "- Assumptions",
    "- Unknowns",
    "",
    "2. Problem Definition (A)",
    "- Real problem",
    "- Who is affected and why it matters",
    "- What happens if we do nothing",
    "- Simplest validation method",
    "",
    "3. Solution Hypothesis (B)",
    "a. Solution Approach (paragraph): high-level approach + user benefit only",
    "b. Number of Screens: minimum required",
    "c. Screen Breakdown for each screen:",
    "- Screen Name",
    "- User Action",
    "- How it solves the problem",
    "",
    "4. Key Assumptions",
    "5. Validation Recommendation",
    "",
    "RULES:",
    "- No UI design",
    "- No technical architecture",
    "- Stay structured and concise",
    "- Tie everything back to the problem",
    "",
    "Return strict JSON only with this schema:",
    JSON.stringify(
      {
        analysis: {
          coreProblem: "string",
          rootCauses: ["string"],
          solutionDirections: ["string"],
          assumptions: ["string"],
          unknowns: ["string"],
        },
        definition: {
          realProblem: "string",
          affectedAndWhy: "string",
          inactionImpact: "string",
          simplestValidation: "string",
        },
        hypothesis: {
          solutionApproach: "string",
          numberOfScreens: 2,
          screenBreakdown: [
            {
              screenName: "string",
              userAction: "string",
              problemResolution: "string",
            },
          ],
        },
        keyAssumptions: ["string"],
        validationRecommendation: "string",
      },
      null,
      2
    ),
    "",
    "INPUT:",
    `Problem Statement: ${input.problemStatement}`,
    `Who is affected: ${input.affectedUsers}`,
    `Business Context: ${input.businessContext || "N/A"}`,
    `Constraints: ${input.constraints || "N/A"}`,
    `Additional Notes: ${input.additionalNotes || "N/A"}`,
  ].join("\n");
}
